### ISSUE TITLE
Stiffness Matrix Update Optimization

### ISSUE THREAD

**Issue by yijiangh** [527897054/FrameFab#11]

**Comment by exiinuh** [comment]
SolveWithGuess with average initiate value of D0 -- no improvement

**Comment by exiinuh** [comment]
coding CG instead of that in Eigen

**Comment by exiinuh** [comment]
A Chebyshev Semi-Iterative Approach for Accelerating Projective and Position-based Dynamics
Huamin Wang∗
The Ohio State University
